---
services:
  pcts-db:
    container_name: pcts-db
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: pcts
    ports:
      - "5432:5432"
    profiles: ['', backend, db]
  pcts-wiremock:
    container_name: pcts-wiremock
    image: wiremock/wiremock:latest
    ports:
      - "8443:8080"
    volumes:
      - ./wiremock:/home/wiremock
    profiles: ['', backend]
  pcts-backend:
    container_name: pcts-backend
    build:
      context: ..
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - pcts-wiremock
      - pcts-db
    environment:
      PCTS_SPRING_DATASOURCE_URL: pcts-db
      SPRING_PROFILES_ACTIVE: dev
    profiles: ['', backend]

  pcts-frontend:
    container_name: pcts-frontend
    depends_on:
      - pcts-backend
    build:
      context: ..
      dockerfile: ./frontend/Dockerfile
    ports:
      - "4200:4200"
    profiles: ['']
