---
services:
  pcts-db:
    container_name: pcts-db
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: pcts
    ports:
      - "5432:5432"
    profiles: ['', backend, db]
  pcts-backend:
    container_name: pcts-backend
    build: ../backend
    ports:
      - "8080:8080"
    depends_on:
      - pcts-db
    environment:
      PCTS_SPRING_DATASOURCE_URL: pcts-db
      SPRING_PROFILES_ACTIVE: dev
    profiles: ['', backend]

  pcts-frontend:
    container_name: pcts-frontend
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
    ports:
      - "4200:4200"
    profiles: ['']
