---
services:
  pcts-db:
    container_name: pcts-db
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: pcts
    ports:
      - "5432:5432"
    profiles: ['', backend, db]

  pcts-backend:
    container_name: pcts-backend
    build:
      context: ..
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - pcts-db
    environment:
      PCTS_SPRING_DATASOURCE_URL: pcts-db
      SPRING_PROFILES_ACTIVE: dev
    profiles: ['', backend]

  pcts-frontend:
    container_name: pcts-frontend
    depends_on:
      - pcts-backend
    build:
      context: ..
      dockerfile: ./frontend/Dockerfile
    ports:
      - "4200:4200"
    profiles: ['']

  keycloak-pitc:
    image: quay.io/keycloak/keycloak:26.3.3
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin26
      - KC_BOOTSTRAP_ADMIN_PASSWORD=keycloak26
    volumes:
      - ./config/realm-export-pitc.json:/opt/keycloak/data/import/realm-pitc.json
    command:
      - start-dev
      - --import-realm
    ports:
      - "8544:8080"
    profiles: ['', backend, db]
