[book]
authors = ["PUZZLE"]
language = "en"
src = "src"
title = "PCTS Tool"

[output.html]
default-theme="light"
preferred-dark-theme="light"
git-repository-url = "https://github.com/puzzle/pcts"

[output.html.print]
enable = false

[preprocessor.plantuml]
#plantuml-cmd="plantuml"
plantuml-cmd="https://www.plantuml.com/plantuml"