---
name: "Reusable - Format"

on:
  workflow_call:
    inputs:
      COMMIT_HASH:
        type: string
        required: false

jobs:
  backend:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.COMMIT_HASH }}

      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: ${{ vars.JAVA_DISTRIBUTION }}
          server-id: github
          settings-path: ${{ github.workspace }}
          cache: 'maven'
          cache-dependency-path: |
            pom.xml
            backend/pom.xml

      - name: Format backend
        run: mvn spotless:check

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.COMMIT_HASH }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Npm install
        run: npm ci

      - name: Format frontend
        run: npm run check-linting:all

  markdownlint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.COMMIT_HASH }}

      - name: Install Ruby
        run: sudo apt-get install ruby-full

      - name: Install markdownlint
        run: sudo gem install mdl

      - name: Markdown linting
        run: |
            find . -name "*.md" \
            -not -path "./CHANGELOG.md" \
            -not -path "./.github/ISSUE_TEMPLATE/*" \
            -print0 | xargs -0 -r mdl
  yamllint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.COMMIT_HASH }}

      - name: Install yamllint
        run: sudo apt-get install -y yamllint

      - name: yaml linting
        run: yamllint .
