---
name: "Reusable - Format"

on:
  workflow_call:
    inputs:
      COMMIT_HASH:
        type: string
        required: false

jobs:
  backend:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.COMMIT_HASH }}

      - name: Set up cache for formatting
        uses: actions/cache@v4.3.0
        with:
          path: "~/.m2/repository"
          key: maven-formatting-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}

      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: ${{ vars.JAVA_DISTRIBUTION }}
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Format backend
        run: mvn spotless:check

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.COMMIT_HASH }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Npm install
        run: npm ci

      - name: Format frontend
        run: npm run check-linting:all

  markdownlint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.COMMIT_HASH }}

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Install markdownlint
        run: sudo gem install mdl

      - name: Markdown linting
        run: |
          find . -name "*.md" \
          -not -path "./.github/ISSUE_TEMPLATE/*" | xargs mdl

  yamllint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.COMMIT_HASH }}

      - name: Install yamllint
        run: sudo apt-get install -y yamllint

      - name: yaml linting
        run: yamllint .
