---
name: "Reusable - Tests"

on:
  workflow_call:
    inputs:
      COMMIT_HASH:
        type: string
        required: false

permissions:
  checks: write
  pull-requests: write

jobs:
  frontend-tests:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.COMMIT_HASH || github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Npm install
        run: npm ci

      - name: Run unit tests
        run: npm run test:ci

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          check_name: "Frontend Test Results"
          comment_mode: 'changes in failures'
          files: |
            frontend/junit.xml

  backend-tests:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.COMMIT_HASH || github.head_ref }}

      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: adopt

      - name: Use Maven to run unit and integration tests
        run: mvn clean verify

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          check_name: "Backend Test Results"
          comment_mode: 'changes in failures'
          files: |
            backend/target/surefire-reports/*.xml
