---
name: "Reusable - Tests"

on:
  workflow_call:
    inputs:
      COMMIT_HASH:
        type: string
        required: false

permissions:
  checks: write
  pull-requests: write

jobs:
  frontend-tests:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.COMMIT_HASH || github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Npm install
        run: npm ci

      - name: Run unit tests
        run: npm run test:ci --coverage

      - name: Upload frontend reports
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: frontend-test-reports
          path: |
            frontend/coverage/lcov.info
            frontend/junit.xml
          retention-days: 1

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          check_name: "Frontend Test Results"
          comment_mode: 'changes in failures'
          files: |
            frontend/junit.xml

  backend-tests:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.COMMIT_HASH || github.head_ref }}

      - name: Set up cache for testing
        uses: actions/cache@v4.3.0
        with:
          path: "~/.m2/repository"
          key: maven-testing-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}

      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: ${{ vars.JAVA_DISTRIBUTION }}

      - name: Use Maven to run unit and integration tests
        run: mvn clean verify

      - name: Upload backend reports
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: backend-test-reports
          path: |
            backend/target/jacoco.exec
            backend/target/surefire-reports/
          retention-days: 1

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          check_name: "Backend Test Results"
          comment_mode: 'changes in failures'
          files: |
            backend/target/surefire-reports/*.xml
